name: flask-sample-deploy
services:
- name: flask-sample-deploy
  routes:
  - path: /
  environment_slug: python
  github:
    repo: TheOtherDavid/flask-sample-deploy
    branch: master
  build_command: pip install -r requirements.txt
  health_check:
    http_path: /health
  run_command: uwsgi --http-timeout 86400 --http :8080 --master --processes 1 --wsgi myproject:app
  http_port: 8080
