name: flask-sample-deploy
services:
- name: flask-sample-deploy
  github:
    repo: TheOtherDavid/flask-sample-deploy
    branch: master
  build_command: pip install -r requirements.txt
  run_command: uwsgi --ini uwsgi.ini && cat /tmp/uwsgi.log
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: python
  envs:
  - key: API_KEY
    scope: RUN_TIME
    value: ${{ secrets.API_KEY }}